'use client';

import { useState } from 'react';
import { Download, Loader2, FileJson, FileType, FileText, Package } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export default function ProExport({ color, rgbArray }) {
    const [loading, setLoading] = useState(false);

    // Helper: Generate ASE (Adobe Swatch Exchange) Binary
    // Note: ASE is a binary format. We construct it byte by byte.
    const createASE = (hex, name, rgb) => {
        const buffer = [];

        // 1. Signature "ASEF"
        buffer.push(0x41, 0x53, 0x45, 0x46);
        // 2. Version 1.0
        buffer.push(0x00, 0x01, 0x00, 0x00);
        // 3. Number of blocks (1 block = 1 color)
        buffer.push(0x00, 0x00, 0x00, 0x01);

        // Block: 0x0001 (Color Entry)
        buffer.push(0x00, 0x01);

        // Block Length (Placeholder, calculated later)
        // Name length (2 bytes) + Name * 2 (UTF-16) + 2 (Null) + 4 (Color Space) + 12 (Values) + 2 (Type)
        const nameLen = name.length + 1; // +1 for null terminator
        const blockLen = 2 + (nameLen * 2) + 4 + 12 + 2;

        // Push Block Length
        buffer.push((blockLen >> 24) & 0xFF, (blockLen >> 16) & 0xFF, (blockLen >> 8) & 0xFF, blockLen & 0xFF);

        // Name Length
        buffer.push((nameLen >> 8) & 0xFF, nameLen & 0xFF);

        // Name (UTF-16 Big Endian)
        for (let i = 0; i < name.length; i++) {
            buffer.push(0x00, name.charCodeAt(i));
        }
        buffer.push(0x00, 0x00); // Null terminator

        // Color Space "RGB "
        buffer.push(0x52, 0x47, 0x42, 0x20);

        // RBG Values (Float 0-1)
        [rgb.r / 255, rgb.g / 255, rgb.b / 255].forEach(val => {
            // Very simpler float packing (Not perfect IEEE 754 generation for brevity, but widely compatible)
            // Ideally use DataView for precise float32 writing
            const view = new DataView(new ArrayBuffer(4));
            view.setFloat32(0, val, false); // Big Endian
            for (let i = 0; i < 4; i++) buffer.push(view.getUint8(i));
        });

        // Type: Global (0x0002)
        buffer.push(0x00, 0x02);

        return new Uint8Array(buffer);
    };

    const handleDownload = async () => {
        setLoading(true);
        try {
            const zip = new JSZip();
            const safeName = color.name.replace(/[^a-z0-9]/gi, '_').toLowerCase();

            // 1. Create ASE File
            // Parse RGB String "rgb(255, 0, 0)" -> {r:255, g:0, b:0}
            // (Assumed rgbArray prop or parsing logic if string passed)

            let r = 0, g = 0, b = 0;
            if (rgbArray) {
                [r, g, b] = rgbArray;
            } else {
                // Fallback parsing if string
            }

            const aseData = createASE(color.hex, color.name, { r, g, b });
            zip.file(`${safeName}.ase`, aseData);

            // 2. Create JSON Data
            const jsonData = {
                name: color.name,
                nativeName: color.nativeName,
                hex: color.hex,
                rgb: `rgb(${r}, ${g}, ${b})`,
                meaning: color.meaning,
                year: new Date().getFullYear(),
                source: "https://imagecolorpickerai.com"
            };
            zip.file(`${safeName}.json`, JSON.stringify(jsonData, null, 2));

            // 3. Create README (The Story)
            const readme = `
${color.name} (${color.nativeName})
--------------------------------------------------
HEX: ${color.hex}
RGB: ${r}, ${g}, ${b}

STORY & MEANING:
${color.meaning}

Cultural Context:
This color is part of the Traditional Chinese Color system, often used in ancient poetry, silk weaving, and porcelain art.

--------------------------------------------------
Generated by Image Color Picker AI
https://imagecolorpickerai.com
`;
            zip.file("README_STORY.txt", readme);

            // Generate ZIP
            const content = await zip.generateAsync({ type: "blob" });
            saveAs(content, `${safeName}_design_kit.zip`);

        } catch (e) {
            console.error("Export failed", e);
            alert("Failed to generate design kit. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <button
            onClick={handleDownload}
            disabled={loading}
            className="flex items-center gap-2 bg-gradient-to-r from-amber-200 to-yellow-400 text-amber-900 px-4 py-2 rounded-lg font-bold shadow-sm hover:shadow-md hover:scale-105 transition-all text-sm disabled:opacity-70 disabled:cursor-not-allowed group border border-amber-300"
            title="Download Pro Design Kit (.ASE, JSON, TXT)"
        >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Package className="w-4 h-4" />}
            <span>{loading ? 'Bundling...' : 'Pro Kit'}</span>
            <span className="hidden group-hover:inline text-[10px] ml-1 opacity-70">
                (.ZIP)
            </span>
        </button>
    );
}
